### ISSUE TITLE
poloto-chrono doesn't build when used in a project

### ISSUE THREAD

**Issue by proycon** [tiby312/poloto-project#206]
Is there something wrong with the latest crate? It doesn't build when cargo added to a project, I get the following error :

```
   Compiling poloto-chrono v0.2.2
error[E0412]: cannot find type `RenderOptionsBound` in this scope
   --> /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/poloto-chrono-0.2.2/src/lib.rs:136:18
    |
136 |         canvas: &RenderOptionsBound,
    |                  ^^^^^^^^^^^^^^^^^^ not found in this scope
```

I'm on rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1) and my `Cargo.toml` has only:

```
[dependencies]
argh = "0.1.10"
csv = "1.2.1"
poloto = "18.0.6"
poloto-chrono = "0.2.2"
```

**Comment by tiby312** [comment]
Oops fixed! Try now. I forgot to update the poloto-chrono crate after i made a change to poloto. Thank you for the heads up.

**Comment by proycon** [comment]
Thanks! that fixes it indeed!
